---
title: "Combine RNAseq read counts"
output: html_document
date: "2025-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in the count summary for 2022 plates (TCDM_1 and TCDM_2)
```{r}
countssummary <- read.table(paste0("/workdir/ssv42/RNAseq/v7alignedreads/allsamples_counts.txt.summary"), header=T) %>%
  column_to_rownames(var="Status")

#extract sample names and remove prefix and suffix
summaryIDs <- colnames(countssummary) %>%
  gsub("X.workdir.ssv42.RNAseq.v7alignedreads.", "", .) %>%
  gsub("^.*_.*_TCDM", "TCDM", .) %>%
  gsub("_[A-Z]+_S.*_trim1.bam$", "", .)
colnames(countssummary) <- summaryIDs

#sum total reads, transform data, and calculate percentage assigned reads
countssummary_t <- rbind(countssummary, "Total_reads"= colSums(countssummary)) %>% t() %>% as.data.frame()
countssummary_t$Percentage_assigned <- countssummary_t$Assigned/countssummary_t$Total_reads

hist(countssummary_t$Total_reads, main="Total Reads")
hist(countssummary_t$Percentage_assigned, main="% Reads Assigned to Genes")

```


Read in the counts matrix
```{r}
countsmatrix <- read.table(paste0("/workdir/ssv42/RNAseq/v7alignedreads/allsamples_counts.txt"), header=T)

#extract sample names
sampleIDs <- colnames(countsmatrix)[7:ncol(countsmatrix)] %>%
  gsub("X.workdir.ssv42.RNAseq.v7alignedreads.", "", .) %>%
  gsub("^.*_.*_TCDM", "TCDM", .) %>%
  gsub("_[A-Z]+_S.*_trim1.bam$", "", .)
colnames(countsmatrix)[7:ncol(countsmatrix)] <- sampleIDs

#extract metadata from sampleID 
sample_metadata <- str_split_fixed(sampleIDs, "_", n=7) %>% as.data.frame()
colnames(sample_metadata) <- c("project","plate","well","family","progeny","root","layer")
sample_metadata$sampleID <- sampleIDs
sample_metadata$plateID <- paste0(sample_metadata$project, "_", sample_metadata$plate)
sample_metadata$genotype <- paste0(sample_metadata$family, "_", sample_metadata$progeny) %>%
  str_replace(., "^(A.*|C.*)_[0-9]$", "\\1") #remove progeny tag from parents
metadata <- sample_metadata %>% dplyr::select(sampleID, plateID, genotype, root, layer)
metadata$timept <- "5MAP" #everything from 2022 harvested at one timepoint
metadata$year <- "2022"

#extract gene metadata
gene_metadata <- countsmatrix[,1:6]
countsmatrix <- countsmatrix[,-c(1:6)]
rownames(countsmatrix) <- gene_metadata$Geneid 

#filter individuals with too few expressed genes (>10 counts / gene for that sample)
#identify genes with >10 copies
ExpressedGeneTFMatrix <- countsmatrix >= 10
GenesExprPerSample <- colSums(ExpressedGeneTFMatrix)
#examine distribution of number of genes expressed per sample
hist(GenesExprPerSample)
#identify & filter out samples with too few genes expressed
cutoff <- 3000
todrop_samples <- which(GenesExprPerSample < cutoff)
hist(GenesExprPerSample)
abline(v=cutoff, col="red", lty="dashed")

#identify & filter out genes not expressed in any of the samples
GenesExprAcrossSamples <- rowSums(ExpressedGeneTFMatrix)
todrop_genes <- which(GenesExprAcrossSamples == 0)

#apply filters
countsmatrixfilt <- countsmatrix[-todrop_genes, -todrop_samples]
dim(countsmatrixfilt) #9862 genes, 159 samples

#re-assign variable names so code can be reused for next dataset
samplemetadata2022 <- metadata %>% filter(sampleID %in% colnames(countsmatrixfilt))
genemetadata2022 <- gene_metadata %>% filter(Geneid %in% rownames(countsmatrixfilt))
countsmatrix2022 <- countsmatrixfilt

saveRDS(countsmatrixfilt, file="/workdir/ssv42/RNAseq/countsmatrix_22_v7aligned_filt.RDS")
```


Test megaLMM
```{r}
#get sample metadata
sample_data <- samplemetadata2022 

#make nxp trait matrix, individuals in rows and genes in columns
Ymat <- t(countsmatrixfilt)

#confirm correct order of individuals across both matrices
sum(rownames(Ymat) != sample_data$sampleID) == 0
```

```{r}
library(MegaLMM)
#set MegaLMM parameters
run_parameters = MegaLMM_control(
  h2_divisions = 20, 
    # Each variance component is allowed to explain between 0% and 100% of the
      # total variation. How many segments should the range [0,100) be divided 
      # into for each random effect?
  burn = 0,  
    # number of burn in samples before saving posterior samples. I set this to 
      # zero and instead run the chain in small chunks, doing the burning manually, a
      # s described below.
  thin = 2,
    # during sampling, we'll save every 2nd sample to the posterior database.
  K = 20 # number of factors. With 19 traits, this is likely way higher than needed.
)

#set up MegaLMM model
MegaLMM_state = setup_model_MegaLMM(
  Y = Ymat,  
    # The n x p trait matrix
  formula = ~ (1|genotype) + plateID + layer,  
    # This is syntax like lme4 for mixed effect models. 
      # We specify a fixed effect of population and a random effect for genotype (Line)
  data = sample_data,         
    # the data.frame with information for constructing the model matrices
  #relmat = list(Line = K), 
    # A list of covariance matrices to link to the random effects in formula.
      # each grouping variable in formula can be linked to a covariance matrix.
      # If so, every level of the grouping variable must be in the rownames of K.
      # additional rows of K not present in data will still be predicted 
        # (and therefore will use memory and computational time!)
  run_parameters=run_parameters,
    # This list of control parameters created above
  run_ID = sprintf('MegaLMM_test')
    # A run identifier. The function will create a folder with this name 
      # and store lots of useful data inside it
)

#define priors for factors
Lambda_prior = list(
    sampler = sample_Lambda_prec_ARD,
      # function that implements the ARD Lambda prior
          # described in Runcie et al 2013 paper.
          #See code to see requirements for this function.
      # other options are:
          # ?sample_Lambda_prec_horseshoe
          # ?sample_Lambda_prec_BayesC
    Lambda_df = 3,
    delta_1   = list(shape = 2, rate = 1),
    delta_2   = list(shape = 3, rate = 1),  # parameters of the gamma distribution giving the expected change in proportion of non-zero loadings in each consecutive factor
      # parameters of the gamma distribution giving the expected change
          # in proportion of non-zero loadings in each consecutive factor
    delta_iterations_factor = 100
      # parameter that affects mixing of the MCMC sampler. This value is generally fine.
  )

#define remaining priors
priors = MegaLMM_priors(
  tot_Y_var = list(V = 0.5,   nu = 5),      
    # Prior variance of trait residuals after accounting for fixed effects and factors
      # See MCMCglmm for meaning of V and nu
  tot_F_var = list(V = 18/20, nu = 20),     
    # Prior variance of factor traits. This is included to improve MCMC mixing, 
      # but can be turned off by setting nu very large
  h2_priors_resids_fun = function(h2s,n)  1,  
    # Function that returns the prior density for any value of the h2s vector 
        # (ie the vector of random effect proportional variances across all random effects. 
        # 1 means constant prior. 
        # n is the number of h2 divisions above (here=20)
        # 1-n*sum(h2s)/n linearly interpolates between 1 and 0, 
            # giving more weight to lower values
  h2_priors_factors_fun = function(h2s,n) 1, 
    # See above. 
        # sum(h2s) linearly interpolates between 0 and 1,
            # giving more weight to higher values
        # Another choice is one that gives 50% weight to h2==0: ifelse(h2s == 0,n,n/(n-1))
  Lambda_prior = Lambda_prior
    # from above
)

#set priors
MegaLMM_state = set_priors_MegaLMM(MegaLMM_state,priors)
```

```{r}
#initialize model
MegaLMM_state = initialize_variables_MegaLMM(MegaLMM_state)
MegaLMM_state$run_parameters$burn = run_parameters$burn

#estimate memory usage
estimate_memory_initialization_MegaLMM(MegaLMM_state)

#proceed with initializing
MegaLMM_state = initialize_MegaLMM(MegaLMM_state,verbose = T)

#specify parameter values to save
MegaLMM_state$Posterior$posteriorSample_params = c('Lambda','F_h2','resid_h2','tot_Eta_prec','B1')
MegaLMM_state$Posterior$posteriorMean_params = 'Eta_mean'

#calulate the genetic (G) and residual (R) covariances, additive heritability of each trait
MegaLMM_state$Posterior$posteriorFunctions = list(
  U = 'U_F %*% Lambda + U_R + X1 %*% B1',
  G = 't(Lambda) %*% diag(F_h2[1,]) %*% Lambda + diag(resid_h2[1,]/tot_Eta_prec[1,])',
  R = 't(Lambda) %*% diag(1-F_h2[1,]) %*% Lambda + diag((1-resid_h2[1,])/tot_Eta_prec[1,])',
  h2 = '(colSums(F_h2[1,]*Lambda^2)+resid_h2[1,]/tot_Eta_prec[1,])/(colSums(Lambda^2)+1/tot_Eta_prec[1,])'
  )

MegaLMM_state = clear_Posterior(MegaLMM_state)

#estimate memory usage over the number of planned iterations
estimate_memory_posterior(MegaLMM_state,100)
```
Burn-in phase
```{r}
n_iter = 100
for(i in 1:5) {
  print(sprintf('Burnin run %d',i))
    # Factor order doesn't "mix" well in the MCMC.
    # We can help it by manually re-ordering from biggest to smallest
  MegaLMM_state = reorder_factors(MegaLMM_state,drop_cor_threshold = 0.6)
    # clear any previous collected samples because we've re-started the chain 
  MegaLMM_state = clear_Posterior(MegaLMM_state)
    # Draw n_iter new samples, storing the chain
  MegaLMM_state = sample_MegaLMM(MegaLMM_state,n_iter)
    # make diagnostic plots
  traceplot_array(MegaLMM_state$Posterior$Lambda,name = file.path(MegaLMM_state$run_ID,'Lambda.pdf'))
  traceplot_array(MegaLMM_state$Posterior$U,name =  file.path(MegaLMM_state$run_ID,'U.pdf'),
                  facet_dim = 3,mask = fold_ID_matrix != 1)
  print(sprintf('Completed %d burnin samples', MegaLMM_state$current_state$nrun))
}
MegaLMM_state = clear_Posterior(MegaLMM_state)
```




Read in phenotype data
```{r}
#2022 harvest for TCDM_1 & TCDM_2
#2023 harvest for TCDM_3 & TCDM_4
```



